---
version: '2'
services:
  db:
    image: mariadb:10.3
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: go
      MYSQL_USER: go
      MYSQL_PASSWORD: 123
