# Configuration for Development Environment

[mariadb]
host = "127.0.0.1"
port = 3333
user = "go"
password = "123"
schema = "go"

[mongodb]
host = "127.0.0.1"
port = 27017

[server]
host = "0.0.0.0"
port = 8000
